services:
  - type: web
    name: shelfsenseai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    releaseCommand: flask db upgrade
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: TIDB_CA_CERT_B64
        sync: false
      - key: GEMINI_API_KEY
        sync: false
