#!/usr/bin/env python
# seed_video_demo.py
# -------------------------------------------------
# SECOND, ISOLATED demo dataset for the final FYP video.
#
# Creates:
#   * ONE dedicated shop : "Segamat Jaya Mini Mart" (Johor / Segamat)
#   * ONE dedicated owner: video@demo.my  (password Demo1234!)
#   * ~11 realistic Malaysian kedai-runcit products
#   * verified ProductMarketMatch links to REAL existing PriceCatcher
#     MarketItems (reuses the 1.97M real observations — no new market data)
#   * realistic inventory (normal / low / out-of-stock) + PriceHistory
#   * two clearly-marked demo MarketRefreshRun rows so /market-data is usable
#
# The recommendation shown in the app is generated by the EXISTING pricing
# engine at seed time (services.pricing_engine.get_price_recommendation) —
# this script never writes a recommendation, it only sets the product/market
# conditions and derives the current selling price from the engine output so
# the Pricing Dashboard naturally shows REDUCE / INCREASE / MAINTAIN.
#
# SAFETY
#   - Does NOT touch "Demo Retail Shop", owner@demo.my, product 1336,
#     existing observations, or existing decisions.
#   - Fully reversible: run `python seed_video_demo.py --clear`.
#   - Re-runnable: seed clears its own shop first.
#   - Rolls back on failure (no half-created demo data).
#
# Usage:
#   ./venv/Scripts/python.exe seed_video_demo.py
#   ./venv/Scripts/python.exe seed_video_demo.py --clear
# -------------------------------------------------
import argparse
import sys
from datetime import datetime, timedelta, timezone

from app import (app, db, Shop, User, Product, PriceHistory, Inventory,
                 MarketSource, MarketItem, ProductMarketMatch,
                 MarketRefreshRun, PricingRecommendationDecision,
                 InventoryAdjustment, Sale, Notification, ShopInvitation)
from services.pricing_engine import get_price_recommendation

# -------------------------------------------------
# Dedicated video-demo identity (do NOT reuse existing demo)
# -------------------------------------------------
DEMO_EMAIL = "video@demo.my"
DEMO_PASSWORD = "Demo1234!"
SHOP_NAME = "Segamat Jaya Mini Mart"
SHOP_STATE = "Johor"
SHOP_DISTRICT = "Segamat"

# -------------------------------------------------
# Product catalogue
#
# Each entry maps to a REAL PriceCatcher MarketItem (with Segamat coverage),
# so market intelligence / evidence / freshness / pricing are all produced by
# the existing engine from real data. `status` is the desired Pricing Dashboard
# bucket; the seed derives the current selling price from the engine output
# (+12% = REDUCE, -7% = INCREASE, exact = MAINTAIN). `selling` overrides that
# for the main product so the on-screen story stays consistent.
# -------------------------------------------------
PRODUCTS = [
    {
        # MAIN VIDEO PRODUCT
        "name": "SABUN PENCUCI KUAT HARIMAU (LEMON)",
        "brand": "Harimau", "category": "PENJAGAAN RUMAH",
        "quantity": 0.4, "unit": "kg",
        "cost": 1.50, "margin": 25.0, "selling": 3.00,
        "stock": 8, "min_stock": 10,
        "market_item_id": 1985,          # 93 obs, 7 premises (Strong, Fresh)
        "unverified": [4325, 4305],      # richer "Suggested Matches" tab
        "history": [(1.40, 2.80, 25.0, 60), (1.50, 3.00, 25.0, 0)],
    },
    {
        "name": "MINYAK MASAK TULEN CAP BURUH",
        "brand": "Cap Buruh", "category": "MINYAK DAN LEMAK",
        "quantity": 1.0, "unit": "kg",
        "cost": 5.90, "margin": 15.0, "status": "MAINTAIN",
        "stock": 25, "min_stock": 8,
        "market_item_id": 1924,          # 1kg, 135 obs, 12 premises
    },
    {
        "name": "GULA PUTIH BERTAPIS KASAR (PELBAGAI JENAMA)",
        "brand": "Generic", "category": "GULA",
        "quantity": 1.0, "unit": "kg",
        "cost": 2.30, "margin": 25.0, "status": "INCREASE",
        "stock": 40, "min_stock": 15,
        "market_item_id": 2017,          # 268 obs, 20 premises
    },
    {
        "name": "TEPUNG GANDUM NGP (BERBUNGKUS, CAP SAUH)",
        "brand": "Cap Sauh", "category": "TEPUNG",
        "quantity": 1.0, "unit": "kg",
        "cost": 2.50, "margin": 20.0, "status": "REDUCE",
        "stock": 30, "min_stock": 10,
        "market_item_id": 2304,          # 242 obs, 20 premises
    },
    {
        "name": "MAGGI MI SEGERA PERISA KARI",
        "brand": "Maggi", "category": "MI SEGERA",
        "quantity": 0.395, "unit": "kg",
        "cost": 4.10, "margin": 22.0, "status": "MAINTAIN",
        "stock": 60, "min_stock": 20,
        "market_item_id": 2188,          # 239 obs, 19 premises
    },
    {
        "name": "100 PLUS (ORIGINAL)",
        "brand": "100 Plus", "category": "TERSEDIA MINUM",
        "quantity": 1.5, "unit": "l",
        "cost": 2.70, "margin": 28.0, "status": "INCREASE",
        "stock": 24, "min_stock": 12,
        "market_item_id": 1951,          # 71 obs, 8 premises
    },
    {
        "name": "SOS CILI MAGGI",
        "brand": "Maggi", "category": "KICAP DAN SOS",
        "quantity": 0.34, "unit": "kg",
        "cost": 3.50, "margin": 23.0, "status": "REDUCE",
        "stock": 30, "min_stock": 10,
        "market_item_id": 1911,          # 261 obs, 20 premises
    },
    {
        "name": "SANTAN KELAPA JENAMA KARA",
        "brand": "Kara", "category": "SANTAN (KOTAK)",
        "quantity": 0.2, "unit": "l",
        "cost": 3.10, "margin": 20.0, "status": "MAINTAIN",
        "stock": 18, "min_stock": 12,
        "market_item_id": 2039,          # 236 obs, 20 premises
    },
    {
        "name": "SUSU SEGAR DUTCH LADY",
        "brand": "Dutch Lady", "category": "TERSEDIA MINUM",
        "quantity": 1.0, "unit": "l",
        "cost": 6.80, "margin": 25.0, "status": "INCREASE",
        "stock": 0, "min_stock": 10,     # out-of-stock demo
        "market_item_id": 2242,          # MODERATE evidence (16 obs, 8 premises)
    },
    {
        "name": "BERAS CAP JASMINE (SST5%)",
        "brand": "Jasmine", "category": "BERAS",
        "quantity": 10.0, "unit": "kg",
        "cost": 24.00, "margin": 10.0, "status": "REDUCE",
        "stock": 15, "min_stock": 5,
        "market_item_id": 2011,          # MODERATE evidence (12 obs, 6 premises)
    },
    {
        # No PriceCatcher match on purpose — demonstrates the
        # "market evidence unavailable / needs matching" empty state.
        "name": "TELUR AYAM GRED A",
        "brand": "Generic", "category": "TELUR",
        "quantity": 30.0, "unit": "pcs",
        "cost": 12.00, "margin": 18.0, "selling": 14.10,
        "stock": 20, "min_stock": 8,
        "market_item_id": None,
    },
]


def _clear_video_demo():
    """Remove ONLY the dedicated video-demo shop/user/products and demo runs."""
    shop = Shop.query.filter_by(name=SHOP_NAME).first()
    removed = {"shop": False, "products": 0, "users": 0, "runs": 0}
    if shop is not None:
        product_ids = [p.id for p in Product.query.filter_by(shop_id=shop.id).all()]
        if product_ids:
            PricingRecommendationDecision.query.filter(
                PricingRecommendationDecision.shop_id == shop.id).delete(
                synchronize_session=False)
            ProductMarketMatch.query.filter(
                ProductMarketMatch.shop_product_id.in_(product_ids)).delete(
                synchronize_session=False)
            InventoryAdjustment.query.filter(
                InventoryAdjustment.product_id.in_(product_ids)).delete(
                synchronize_session=False)
            Sale.query.filter(Sale.product_id.in_(product_ids)).delete(
                synchronize_session=False)
            PriceHistory.query.filter(
                PriceHistory.product_id.in_(product_ids)).delete(
                synchronize_session=False)
            Inventory.query.filter(Inventory.product_id.in_(product_ids)).delete(
                synchronize_session=False)
            Product.query.filter(Product.shop_id == shop.id).delete(
                synchronize_session=False)
            removed["products"] = len(product_ids)
        user_ids = [u.id for u in User.query.filter_by(shop_id=shop.id).all()]
        if user_ids:
            Notification.query.filter(
                Notification.user_id.in_(user_ids)).delete(
                synchronize_session=False)
        ShopInvitation.query.filter(
            ShopInvitation.shop_id == shop.id).delete(synchronize_session=False)
        User.query.filter(User.shop_id == shop.id).delete(synchronize_session=False)
        removed["users"] = len(user_ids)
        db.session.delete(shop)
        removed["shop"] = True
    # Demo-only refresh history (clearly marked, never touches real runs)
    n = MarketRefreshRun.query.filter_by(triggered_by="demo").delete(
        synchronize_session=False)
    removed["runs"] = n
    db.session.commit()
    return removed


def _latest_observed_at(source_name):
    from sqlalchemy import text
    row = db.session.execute(text(
        "SELECT MAX(o.observed_at) FROM market_price_observation o "
        "JOIN market_item mi ON mi.id=o.market_item_id "
        "JOIN market_source ms ON ms.id=mi.source_id "
        "WHERE ms.name=:n"), {"n": source_name}).scalar()
    return row


def _selling_for_status(recommended, cost, status):
    """Derive the current selling price that produces the desired status.

    The recommendation does NOT depend on the current selling price, so
    setting it here only changes the REDUCE/INCREASE/MAINTAIN bucket.
    """
    r = float(recommended)
    if status == "REDUCE":
        return round(r * 1.12, 2)
    if status == "INCREASE":
        # keep the current price above the 5% cost floor
        return round(max(r * 0.93, float(cost) * 1.10), 2)
    return round(r, 2)  # MAINTAIN


def seed():
    created = []
    with app.app_context():
        print("== ShelfSenseAI video-demo seed ==")
        print("-- clearing any previous video-demo data --")
        _clear_video_demo()

        try:
            shop = Shop(name=SHOP_NAME, state=SHOP_STATE, district=SHOP_DISTRICT)
            db.session.add(shop)
            db.session.flush()

            owner = User(email=DEMO_EMAIL, role="owner", shop_id=shop.id)
            owner.set_password(DEMO_PASSWORD)
            db.session.add(owner)
            db.session.flush()
            print(f"   + shop '{SHOP_NAME}' (id={shop.id}, {SHOP_STATE}/{SHOP_DISTRICT})")
            print(f"   + user {DEMO_EMAIL} (owner, hashed password)")

            for spec in PRODUCTS:
                p = Product(
                    name=spec["name"], brand=spec.get("brand"),
                    category=spec.get("category"),
                    quantity=spec["quantity"], unit=spec["unit"],
                    cost_price=spec["cost"], selling_price=spec["cost"],
                    target_margin=spec["margin"], baseline_margin=spec["margin"],
                    shop_id=shop.id,
                )
                db.session.add(p)
                db.session.flush()

                # verified match to a REAL existing PriceCatcher MarketItem
                if spec.get("market_item_id"):
                    mi = db.session.get(MarketItem, spec["market_item_id"])
                    if mi is None:
                        raise RuntimeError(
                            f"MarketItem {spec['market_item_id']} not found for {spec['name']}")
                    db.session.add(ProductMarketMatch(
                        shop_product_id=p.id, market_item_id=mi.id,
                        confidence_score=1.00, match_type="manual",
                        is_verified=True, is_rejected=False))
                for mid in spec.get("unverified", []):
                    if db.session.get(MarketItem, mid) is not None:
                        db.session.add(ProductMarketMatch(
                            shop_product_id=p.id, market_item_id=mid,
                            confidence_score=0.64, match_type="fuzzy",
                            is_verified=False, is_rejected=False))
                db.session.flush()

                # derive the current selling price from the REAL engine
                if spec.get("selling") is not None:
                    selling = float(spec["selling"])
                else:
                    rec = get_price_recommendation(p.id, shop=shop, skip_llm=True)
                    selling = _selling_for_status(
                        rec["recommended_price"], spec["cost"], spec["status"])
                p.selling_price = selling

                # inventory
                db.session.add(Inventory(
                    shop_id=shop.id, product_id=p.id,
                    current_stock=spec["stock"], minimum_stock=spec["min_stock"]))

                # price history (initial snapshot, consistent with current state)
                history = spec.get("history")
                if history:
                    for cost, sell, margin, days_ago in history:
                        db.session.add(PriceHistory(
                            product_id=p.id, cost_price=cost,
                            selling_price=sell, target_margin=margin,
                            created_at=datetime.now(timezone.utc)
                            - timedelta(days=days_ago)))
                else:
                    db.session.add(PriceHistory(
                        product_id=p.id, cost_price=spec["cost"],
                        selling_price=selling, target_margin=spec["margin"]))

                created.append((p.id, spec["name"], spec.get("status") or "EXPLICIT",
                                float(p.selling_price)))

            # minimum safe /market-data metadata (clearly marked 'demo')
            now = datetime.now(timezone.utc)
            started = now - timedelta(hours=6)
            for source in ("pricecatcher", "manamurah"):
                db.session.add(MarketRefreshRun(
                    source_name=source, started_at=started, finished_at=started,
                    status="success", inserted=0, updated=0, duplicates_skipped=0,
                    rejected=0, errors=0,
                    latest_observed_at=_latest_observed_at(
                        "PriceCatcher" if source == "pricecatcher" else "ManaMurah"),
                    error_message=None, triggered_by="demo"))

            db.session.commit()
            print("   + products, verified matches, inventory, price history")
            print("   + 2 demo MarketRefreshRun rows (triggered_by='demo')")
            print("\n[OK] Video demo ready.")
            for pid, name, status, sell in created:
                print(f"   id={pid:<6} RM{sell:<7.2f} target={status:<9} {name}")
            print(f"\n   Login : {DEMO_EMAIL} / {DEMO_PASSWORD}")
            print(f"   Shop  : {SHOP_NAME}")
        except Exception:
            db.session.rollback()
            print("[FAILED] seed rolled back — no partial data was written.")
            raise


def main():
    parser = argparse.ArgumentParser(description="Seed/clear the ShelfSenseAI video-demo dataset.")
    parser.add_argument("--clear", action="store_true",
                        help="Remove the video-demo shop/user/products and demo runs only.")
    args = parser.parse_args()
    if args.clear:
        with app.app_context():
            removed = _clear_video_demo()
            print("[OK] cleared video demo:", removed)
    else:
        seed()


if __name__ == "__main__":
    main()
